name: amora
description: "A private, romantic-themed Flutter app for a couple to store memories and personal information"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  email_validator: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
  uuid: ^4.5.0
  path: ^1.8.0
  undo: ^1.0.0
  image: ^4.0.0
  share_plus: ^7.0.0
  lottie: ^3.0.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  image_path: "assets/icon/app-icon.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/status/
    - assets/images/backgrounds/
    - assets/images/misc/
    - assets/lottie/
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Bold.ttf
    - assets/fonts/Montserrat-SemiBold.ttf
