name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # Matches your local version
          channel: 'stable'
          cache: true

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Generate Hive code
      - name: Generate Hive code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Step 6: Analyze code (linting)
      - name: Run Flutter analyze
        run: flutter analyze

      # Step 7: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 8: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: amora-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
