name: Romantic App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: "3.22.4" # Your specific version
  JAVA_VERSION: "17" # Required for Flutter 3.22.x

jobs:
  setup:
    name: Setup & Validate
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}
      
      - name: Flutter Doctor
        run: flutter doctor -v

  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings
      
      - name: Check Formatting
        run: flutter format --set-exit-if-changed .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: analyze
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      - name: Run Tests
        run: flutter test --coverage
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        if: github.ref == 'refs/heads/main'

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release \
            --split-per-abi \
            --no-tree-shake-icons \
            --dart-define=APP_ENV=production
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: romantic-app
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 5

  release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: romantic-app
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-armeabi-v7a-release.apk
            app-arm64-v8a-release.apk
          tag_name: v1.0.${{ github.run_number }}
          name: "Romantic App v1.0.${{ github.run_number }}"
          body: |
            💖 New update for couples! 💖
            
            - Share more love
            - Improved romantic moments
            - Better connection features
          draft: false
          prerelease: false
