name: Romantic App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.22.1"  # Confirmed stable version
  JAVA_VERSION: "17"

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('pubspec.lock') }}
      
      - name: Verify Setup
        run: |
          java -version
          flutter --version

  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Flutter Analyze
        run: |
          flutter pub get
          flutter analyze --fatal-infos --fatal-warnings
      
      - name: Check Formatting
        run: flutter format --set-exit-if-changed .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Tests
        run: |
          flutter pub get
          flutter test --coverage
      
      - name: Upload Coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Release APK
        run: |
          flutter pub get
          flutter build apk --release \
            --split-per-abi \
            --no-tree-shake-icons \
            --dart-define=APP_ENV=production
      
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: romantic-app-apks
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7

  release:
    name: Create GitHub Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download APKs
        uses: actions/download-artifact@v3
        with:
          name: romantic-app-apks
          path: release-apks/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-apks/app-armeabi-v7a-release.apk
            release-apks/app-arm64-v8a-release.apk
          tag_name: v1.0.${{ github.run_number }}
          name: "Amora v1.0.${{ github.run_number }}"
          body: |
            💖 New Romantic Update! 💖
            
            Build Number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
            
            Features:
            - More love notes
            - Enhanced memories
            - Smoother animations
          draft: false
          prerelease: false
